# fly.toml app configuration file generated for photostudio-rainbow on 2023-11-07T15:12:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "photostudio-rainbow"
primary_region = "waw"

[build]
  image = "dzavialov1409/photostudio"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
